/* This file was generated by SableCC (http://www.sablecc.org/). */

package latexToGLSL.node;

import latexToGLSL.semantic.IAEquacao;

public abstract class PAEquacao extends Node implements IAEquacao
{
	/*
	 * Adiciona implementação da interface IAEquacao para que o 
	 * método getTkIdentificador possa ser acessado pela classe concreta
	 * AAEquacao que extende esta (PAEquacao)
	 */
    // Empty body
}
